plugins {
    id 'java'
    id 'jacoco'
    id 'application'
}
repositories {
    mavenCentral()
}
dependencies {
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}
test {
    useJUnitPlatform()
    testLogging {
        events "passed", "skipped", "failed"
    }
}
application {
    mainClass = 'ru.nsu.egorov.Main'
}